export const copies = {
  zh: {
    eyebrow: "真实 React 示例",
    title: "实时操作，观察状态变化",
    intro: {
      before: "下面的界面直接使用",
      packageName: "@zhuangtai-js/react",
      after: "。选择示例即可操作并查看关键代码。",
    },
    examplesLabel: "选择示例",
    preview: "实时预览",
    source: "关键实现",
    examples: { counter: "计数器", tasks: "任务清单", preferences: "偏好设置" },
    counter: {
      title: "计数器",
      description: "一个 atom 保存计数，computed 自动生成双倍值。",
      current: "当前值",
      doubled: "双倍值",
      decrease: "减少 1",
      increase: "增加 1",
      reset: "重置",
    },
    tasks: {
      title: "今天要做什么？",
      description: "添加、完成或筛选任务，列表与统计会同步更新。",
      placeholder: "输入新任务",
      add: "添加任务",
      filterLabel: "筛选任务",
      filters: { all: "全部", active: "待完成", done: "已完成" },
      empty: "这个筛选条件下还没有任务。",
      remove: "删除",
      removeLabel: (title: string) => `删除：${title}`,
      summary: (done: number, total: number) => `已完成 ${done} / ${total}`,
    },
    preferences: {
      title: "阅读偏好",
      description: "选择会写入浏览器存储，刷新页面后仍然保留。",
      theme: "界面主题",
      density: "内容密度",
      light: "浅色",
      dark: "深色",
      comfortable: "舒适",
      compact: "紧凑",
      saved: "已保存到当前浏览器",
      fallback: "当前浏览器禁止存储，本次会话仍可正常使用",
      previewTitle: "项目概览",
      previewBody: "重要状态一目了然。",
    },
  },
  en: {
    eyebrow: "REAL REACT EXAMPLES",
    title: "Interact and watch state update",
    intro: {
      before: "These interfaces run directly on",
      packageName: "@zhuangtai-js/react",
      after: ". Pick an example, try it, and inspect the code.",
    },
    examplesLabel: "Choose an example",
    preview: "Live preview",
    source: "Implementation",
    examples: { counter: "Counter", tasks: "Task list", preferences: "Preferences" },
    counter: {
      title: "Counter",
      description: "One atom stores the count while computed derives the doubled value.",
      current: "Current",
      doubled: "Doubled",
      decrease: "Decrease by 1",
      increase: "Increase by 1",
      reset: "Reset",
    },
    tasks: {
      title: "What needs doing?",
      description: "Add, complete, or filter tasks; the list and summary update together.",
      placeholder: "Enter a new task",
      add: "Add task",
      filterLabel: "Filter tasks",
      filters: { all: "All", active: "Active", done: "Completed" },
      empty: "No tasks match this filter yet.",
      remove: "Remove",
      removeLabel: (title: string) => `Remove: ${title}`,
      summary: (done: number, total: number) => `${done} of ${total} completed`,
    },
    preferences: {
      title: "Reading preferences",
      description: "Your choices are stored in the browser and remain after a refresh.",
      theme: "Theme",
      density: "Density",
      light: "Light",
      dark: "Dark",
      comfortable: "Comfortable",
      compact: "Compact",
      saved: "Saved in this browser",
      fallback: "Storage is unavailable; preferences still work for this session",
      previewTitle: "Project overview",
      previewBody: "See every important state at a glance.",
    },
  },
} as const;
